-- THE NUMBER OF LEVELS 
numL=1
-- THE NUMBER OF TUNNELS
numT=4
-- THE NUMBER OF SHAFTS TO EXCAVATE
numS=16
-- HOW MANY LEVELS TO SKIP
skipL=0
-- HOW MANY TUNNELS TO SKIP
skipT=0
-- HOW MANY SHAFTS TO SKIP
skipS=0
-- THE DIRECTION OF THE NEXT LEVEL (UP or DOWN)
nextDirL=up
-- THE DIRECTION OF THE NEXT TUNNEL (LEFT or RIGHT)
nextDirT=left
-- THE HEIGHT OF THE LEVELS/TUNNELS
height=3
-- THE NUMBER OF BLOCKS BETWEEN EACH SHAFT
blocksBetweenShafts=3
-- HOW MANY BLOCKS WILL THE TURTLE MOVE BEFORE DIGGING THE FIRST SHAFT
firstShaftOffset=4
-- THE NUMBER OF BLOCKS THE EVEN LEVEL SHAFTS WILL BE OFFSET
evenLevelOffset=2
-- DOES THE TURTLE ALSO PLACE TORCHES
placeTorches=false
-- IS THERE A SINGLE DROPOFF CHEST (true) OR ONE PER DIRECTION, PER LEVEL (false)
singleChest=false
-- THE RADIUS OF THE CIRCLE ON WHICH THE REFUELING STATIONS ARE POSITIONED
centerRadius=5
-- DOES THE TURTLE NEED TO DIG THE SIDES ASWELL
digSidesToo=false
-- THE NUMBER OF BLOCK TYPES THE TURTLE WILL _NOT_ DIG UNLESS NEEDED
numIgnoreBlocks=6
-- DOES THE TURTLE REQUIRE FUEL TO OPERATE?
requiresFuel=true
-- THE AMOUNT OF FUEL THE TURTLE WILL STORE BEFORE HEADING OF TO A SHAFT
departureFuel=1200
-- THE AMOUNT OF FUEL AT WHICH THE TURTLE WILL RETURN TO DROPOFF
returnFuel=200
-- THE DIRECTION OF THE FUEL ITEMS (IN THE REFUELING STATION)
fuelSuckDir=up
-- THE DIRECTION WHERE THE TURTLE WILL DROP LEFTOVERS (BUCKETS)
fuelDropDir=down
-- THE DIRECTION WHERE THE TURTLE WILL DROP ANY MINED ITEMS
itemDropDir=down
-- THE DIRECTION OF THE TORCHES
torchSuckDir=right
-- THE DIRECTION OF THE IGNORE BLOCKS
ignoreDir=left